version: '3'
services:
  # 服务名称
  react-admin-example:
    # 镜像:版本
    image: nginx
    # 容器名
    container_name: nginx_react-admin-example
    restart: unless-stopped
    # 映射容器80端口到本地3000端口
    ports:
      - "3000:80"
    # 数据卷 映射本地文件到容器
    volumes:
      # 映射nginx.conf文件到容器的/etc/nginx/conf.d目录并覆盖default.conf文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # 映射build文件夹到容器的/usr/share/nginx/html文件夹
      - ../docs:/usr/share/nginx/html
    # 覆盖容器启动后默认执行的命令。
    #command: /bin/bash -c "nginx -g 'daemon off;'"

  react-admin-example.benxjc:
    # 镜像:版本
    image: benxjc/react-admin-example:mockjs
    container_name: benxjc_react-admin-example_mockjs
    restart: unless-stopped
    # 映射容器80端口到本地3000端口
    ports:
      - "3100:80"